### ISSUE TITLE
Delete?

### ISSUE THREAD

**Issue by KasperAndersson** [umweltdk/resource-cost#1]
Is this still used?

**Comment by jdpnielsen** [comment]
It's not used, but i don't see any reason to delete it - we have unlimited repos these days. I would just add an 'archived' tag to it.

**Comment by KasperAndersson** [comment]
@jdpnielsen Cool, just getting this https://github.com/umweltdk/resource-cost/network/dependencies warning.

**Comment by jdpnielsen** [comment]
Roger. I have disabled the alerts.
